Repository codestates-seb/abc02_001, pull requests merged in 2024-01, with the labels that each got.

#65 [FE] 공통 유틸리티, 컴포넌트, 레이아웃 작성 완료 및 merge
  Client/src/App.js
  Client/src/components/Common/PageTitle.jsx
  Client/src/layout/PageLayout.jsx
  Client/src/styles/reset.css
  Client/src/utils/getNotify.js
Labels: Feature, Init, [FE]

#66 [FE] 버튼 컴포넌트 완료 marge
  Client/src/components/Common/Button.jsx
Labels: Feature, Remane, [FE]

#75 [FE]방명록 마크업 CSS 완성
  Client/src/components/Common/Button.jsx
  Client/src/components/GestBook/GB_Comment.jsx
  Client/src/components/GestBook/GB_CommentBox.jsx
  Client/src/components/GestBook/GB_TextBox.jsx
  Client/src/pages/GuestBook/GuestBook.jsx
Labels: Feature, [FE]

#94 [FE] 반페이지, 쪽지페이지 마크업 완료
  Client/src/assets/message.svg
  Client/src/assets/openMsg.svg
  Client/src/components/Band/BandJoin.jsx
  Client/src/components/Band/BandList.jsx
  Client/src/components/Band/BandSearch.jsx
  Client/src/components/Common/Button.jsx
  Client/src/components/Common/Pagination.jsx
  Client/src/components/GestBook/GB_Comment.jsx
  Client/src/components/GestBook/GB_CommentBox.jsx
  Client/src/components/GestBook/GB_TextBar.jsx
  Client/src/components/GestBook/GB_TextBox.jsx
  Client/src/components/Note/NoteMessageList.jsx
  Client/src/components/Note/NoteMessageModal.jsx
  Client/src/components/Note/NoteUserNickname.jsx
  Client/src/pages/Band/Band.jsx
  Client/src/pages/GuestBook/GuestBook.jsx
  Client/src/pages/Note/Note.jsx
Labels: Feature, Fix, Desigin, Style, Remane, Remove, [FE]

#96 로그인 페이지, 회원정보 수정 페이지, 마이페이지, 소개 페이지, 로딩 스피너 마크업 & CSS
  Client/src/components/Common/Button.jsx
  Client/src/components/Common/PageTitle.jsx
  Client/src/components/Common/SendNoteButton.jsx
  Client/src/components/Common/Spinner.jsx
  Client/src/components/Member/MemberForm.jsx
  Client/src/components/Member/MemberFormButtonBlock.jsx
  Client/src/components/Member/MemberFormCheckbox.jsx
  Client/src/components/Member/MemberQuestionBlock.jsx
  Client/src/components/Member/MemeberFormInput.jsx
  Client/src/components/MyPage/ButtonStyleLink.jsx
  Client/src/components/MyPage/DivisionLine.jsx
  Client/src/components/MyPage/HiddenTitle.jsx
  Client/src/components/MyPage/MyPageChangeInfo.jsx
  Client/src/components/MyPage/MyPageFriendList.jsx
  Client/src/components/MyPage/MyPageProfile.jsx
  Client/src/components/MyPage/MyPageRecommend.jsx
  Client/src/components/MyPage/MyPageSection.jsx
  Client/src/components/MyPage/NickNameTag.jsx
  Client/src/components/MyPage/NickNameTagBig.jsx
  Client/src/components/MyPage/StyleCodePalette.jsx
  Client/src/layout/IntroLayout.jsx
  Client/src/layout/NavButton.jsx
  Client/src/layout/NavList.jsx
  Client/src/pages/GuestBook/GuestBook.jsx
  Client/src/pages/Introduction/Introduction.jsx
  Client/src/pages/Member/Join.jsx
  Client/src/pages/Member/Login.jsx
  Client/src/pages/Member/Membership.jsx
  Client/src/pages/MyPage/MyPage.jsx
Labels: Feature, Refactor, Remane, [FE]

#105 [FE] 기능 추가 및 파일이동 수정
  Client/.gitignore
  Client/note.json
  Client/package.json
  Client/src/components/Band/BandFunction.jsx
  Client/src/components/Band/BandJoin.jsx
  Client/src/components/Band/BandList.jsx
  Client/src/components/Band/BandSearch.jsx
  Client/src/components/Band/BandSearchButton.jsx
  Client/src/components/Band/BandStyle.jsx
  Client/src/components/Band/ClassSearchForm.jsx
  Client/src/components/Band/GradeSearchForm.jsx
  Client/src/components/Band/SchoolSearchForm.jsx
  Client/src/components/Band/SchoolTypeSelect.jsx
  Client/src/components/Common/Pagination.jsx
  Client/src/components/Common/SendNoteButton.jsx
  Client/src/components/GestBook/GB_Comment.jsx
  Client/src/components/GestBook/GB_CommentBox.jsx
  Client/src/components/GestBook/GB_TextBar.jsx
  Client/src/components/GestBook/GB_TextBox.jsx
  Client/src/pages/Band/Band.jsx
  Client/src/pages/GuestBook/GuestBook.jsx
Labels: Feature, Fix, Style, Refactor, Remane, Remove, [FE]

#109 Fe member dev
  Client/src/App.js
  Client/src/components/MyPage/MyPageChangeInfo.jsx
  Client/src/components/MyPage/MyPageFriendList.jsx
  Client/src/components/MyPage/MyPageNoBand.jsx
  Client/src/components/MyPage/MyPageProfile.jsx
  Client/src/components/MyPage/NoFriends.jsx
  Client/src/components/MyPage/RecommendTitle.jsx
  Client/src/components/MyPage/StyleCodePalette.jsx
  Client/src/components/Routes/BandRoute.jsx
  Client/src/components/Routes/LandingRoute.jsx
  Client/src/components/Routes/PrivateRoute.jsx
  Client/src/components/Routes/PublicRoute.jsx
  Client/src/index.js
  Client/src/layout/Navigation.jsx
  Client/src/pages/Member/Join.jsx
  Client/src/pages/Member/Login.jsx
  Client/src/pages/MyPage/MyPage.jsx
  Client/src/routes.js
Labels: Feature, Fix, Refactor, Remane, [FE]

#110 Fe gb pocket 베포전 머지
  Client/src/components/Band/BandStyle.jsx
  Client/src/components/GestBook/GB_Comment.jsx
  Client/src/pages/Band/Band.jsx
  Client/src/pages/GuestBook/GuestBook.jsx
Labels: Feature, Fix, Refactor, [FE]

#115 [FE]✨Feat : head의 title, description 설정 #88
  Client/public/index.html
Labels: Fix, [FE]
